### ISSUE TITLE
Configuration file instead of flags

### ISSUE THREAD

**Issue by shyim** [canonical/chisel#112]
I would like to have a simple configuration file instead of passing a lot of parameters. I could imagine something like:

```yaml
source: ubuntu-22.04
packages:
  - dash-bins
  - ....
```

In that way, I would get rid of having a shell script with all the flags
